name: wonders of architecture
favicon: null
layout_spectrum: 0.21451594517566264
typography_spectrum: 0.8366053528152406
title: Wonders of Architecture
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#750000'
    - '#645214'
    - '#82d5fd'
  brandStrength: 1
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 1
purpose: []
