name: wonders of architecture
favicon: null
layout_spectrum: 0.21451594517566264
typography_spectrum: 0.8366053528152406
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.13516767648980021
  lightness: 0.054961201967671514
  saturation: 0.08238875051029027
  rhythmicContrast: 0.38531345152296126
purpose: []
